name: 'Action Redis'
description: 'Greet someone and record the time'
inputs:
  redis-version:
    description: 'Redis version'
    default: '6.2.6'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'