name: Node.js versions

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Pack tests
        run: npx npt pack -c .package-tester.json
      - uses: actions/upload-artifact@master
        with:
          name: package-tests
          path: tmp
  test:
    runs-on: ${{ matrix.os }}
    env:
      YARGS_MIN_NODE_VERSION: ${{ matrix.node }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node: [14]
        include:
          - os: windows-latest
            redis: "2"
            redis_user: ''
    needs: build
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Show configuration
        run: |
          npm config get user-agent
      # - name: Start Redis
      #   uses: superchargejs/redis-github-action@1.1.0
      #   with:
      #     redis-version: "6"
      - uses: actions/checkout@master
      - uses: ./.github/actions/action-redis
        with: 
          redis-version: "${{matrix.redis}}"
      - uses: actions/download-artifact@master
        with:
          name: package-tests
          path: tmp
      - name: Install dependencies
        working-directory: tmp/package-tests
        run: npm install
      - name: Run tests
        env:
          REDIS_USER: ${{ matrix.redis_user }}
        working-directory: tmp/package-tests
        run: npm run test